import { useState } from 'react';
import Layout from '../components/Layout';
function validarNome(v){const p=v.trim().split(/\s+/);return p.length>=2&&p.every(x=>x.length>=2&&/^[A-Za-zÀ-ÖØ-öø-ÿ]+$/.test(x));}
function validarEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
export default function Contato(){const [f,setF]=useState({nome:'',email:'',mensagem:''});const [erros,setErros]=useState({});const [ok,setOk]=useState(false);const set=(k,v)=>setF(x=>({...x,[k]:v.slice(0,k==='mensagem'?500:120)}));
 const submit=e=>{e.preventDefault();const n={};if(!validarNome(f.nome))n.nome='Insira nome e pelo menos um sobrenome (mínimo de 2 letras cada, sem números).';if(!validarEmail(f.email))n.email='Informe um e-mail válido.';if(f.mensagem.trim().length<10)n.mensagem='A mensagem deve ter pelo menos 10 caracteres.';setErros(n);if(!Object.keys(n).length){setOk(true);setF({nome:'',email:'',mensagem:''});}};
 return <Layout title="Fale Conosco" subtitle="Envie suas sugestões ou relate dificuldades de acesso ao app."><main className="cartao-fartura"><p className="text-sm text-[color:var(--texto-suave)] mb-4">Todos os campos são rigorosamente validados antes do envio.</p>{ok&&<div className="mural-banner mural-banner--sucesso mb-4 flex items-center gap-2"><span>✓</span> Mensagem enviada com sucesso! Obrigado pelo contato.</div>}
 <form onSubmit={submit} className="space-y-4" noValidate><div><label className="block text-xs font-bold uppercase text-[color:var(--texto-suave)] mb-1">Nome Completo</label><input value={f.nome} onChange={e=>set('nome',e.target.value)} className="w-full p-3 rounded-xl text-sm focus:outline-none" placeholder="Ex: João da Silva"/>{erros.nome&&<p className="mural-erro mt-1">{erros.nome}</p>}</div>
 <div><label className="block text-xs font-bold uppercase text-[color:var(--texto-suave)] mb-1">E-mail</label><input value={f.email} onChange={e=>set('email',e.target.value)} className="w-full p-3 rounded-xl text-sm focus:outline-none" placeholder="Ex: joao@gmail.com"/>{erros.email&&<p className="mural-erro mt-1">{erros.email}</p>}</div>
 <div><div className="flex justify-between items-center mb-1"><label className="block text-xs font-bold uppercase text-[color:var(--texto-suave)]">Mensagem</label><span className="text-xs text-[color:var(--texto-suave)]">{f.mensagem.length}/500</span></div><textarea value={f.mensagem} onChange={e=>set('mensagem',e.target.value)} rows="5" maxLength="500" className="w-full p-3 rounded-xl text-sm focus:outline-none" placeholder="Digite sua mensagem de feedback ou dúvida aqui..."/>{erros.mensagem&&<p className="mural-erro mt-1">{erros.mensagem}</p>}</div><button type="submit" className="botao botao--principal w-full py-3">Enviar Feedback</button></form></main></Layout>}
